{% set name = "xicam" %}
{% set version = "2.2.3" %}
{% set sha256 = "c2bf6f39b85a68e6e8aa6e917b225e72ce093474be3e8f2f0b4f9ccfcb29e2ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/synchrotrons/Xi-cam/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py<36]
  entry_points:
    - xicam=run_xicam:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - astropy
    - databroker
    - numpy
    - pyqt >=5
    - qdarkstyle
    - qtmodern
    - qtpy
    - signalslot
    - xicam.core
    - xicam.gui
    - xicam.plugins 
    - yapsy

test:
  imports:
    - xicam

about:
  home: https://github.com/synchrotrons/Xi-cam
  license: BSD 3-clause
  license_file: LICENSE.md
  summary: An extensible platform for synchrotron data reduction, visualization, and management
